### ISSUE TITLE
Bug: Same user profile always returned #22

### ISSUE THREAD

**Issue by SubtleCo** [NSS-Evening-Cohort-17/bangazon-llc-SMH#22]
When an authenticated client submits a GET request to the /profile/my-profile resource, an incorrect user profile is returned. Additionally, the same user profile is returned regardless of the authentication token provided.

**Comment by snagel33** [comment]
Edit line 31 from:

serializer = UserSerializer(User.objects.first())

to: 

serializer = UserSerializer(request.user)
