### ISSUE TITLE
Bug: Incorrect result for minimum products sold #21

### ISSUE THREAD

**Issue by SubtleCo** [NSS-Evening-Cohort-17/bangazon-llc-SMH#5]
Clients can request a list of products that have sold at least the specified number of items using the following URL scheme.

http://localhost:8000/products?number_sold=20

This should return products that have been sold 20+ times. This feature is currently not working.

**Comment by snagel33** [comment]
Edited lines 171-173 in product_view.py:

if number_sold is not None:
        products = products.annotate(
                number_sold=Count('orders')).filter(number_sold__gte=number_sold)

**Comment by snagel33** [comment]
Works in Bangazon API
