### ISSUE TITLE
REPORT: Favorited sellers by customer

### ISSUE THREAD

**Issue by SubtleCo** [NSS-Evening-Cohort-17/bangazon-llc-SMH#9]
Marketing needs to know if users are actually using the favorited feature. Create a report showing all users that have favorited a store.

Customer name header
Bulleted list of store names

**Comment by snagel33** [comment]
SELECT first_name, last_name, name
FROM auth_user
JOIN bangazon_api_favorite ON auth_user.id = bangazon_api_favorite.customer_id
JOIN bangazon_api_store ON bangazon_api_favorite.store_id = bangazon_api_store.id
ORDER BY first_name;
